# We're using version 3.7 of the Docker Compose file format
version: "3.7"

# Define services/containers
services:
# php container
  Kt-node:
    build: .
    volumes: 
      - ./:/home/node/app
    ports:
      - 3003:3003
      
# Define networks
networks:
  mysql-network: